// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGZ6yqYQsEeyF_wUn8y6MoktVv72n0APE',
    appId: '1:630311462221:web:280bb77a0a9c4993650304',
    messagingSenderId: '630311462221',
    projectId: 'medicalchatgroup',
    authDomain: 'medicalchatgroup.firebaseapp.com',
    storageBucket: 'medicalchatgroup.appspot.com',
    measurementId: 'G-9KEP3CTWTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_M46c_jIqqlqKR2O8ygXu_TcyrXPMB-A',
    appId: '1:630311462221:android:6ddad812fa04d163650304',
    messagingSenderId: '630311462221',
    projectId: 'medicalchatgroup',
    storageBucket: 'medicalchatgroup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpbHE_MJIBGSv5ZQv2ii681E4bD25PE0g',
    appId: '1:630311462221:ios:3ce548e9f956137a650304',
    messagingSenderId: '630311462221',
    projectId: 'medicalchatgroup',
    storageBucket: 'medicalchatgroup.appspot.com',
    iosClientId: '630311462221-0162kjpmrgr05lavfeievjp93tur0qma.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalChatGroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpbHE_MJIBGSv5ZQv2ii681E4bD25PE0g',
    appId: '1:630311462221:ios:3ce548e9f956137a650304',
    messagingSenderId: '630311462221',
    projectId: 'medicalchatgroup',
    storageBucket: 'medicalchatgroup.appspot.com',
    iosClientId: '630311462221-0162kjpmrgr05lavfeievjp93tur0qma.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalChatGroup',
  );
}
